### ISSUE TITLE
Base database schema is missing. Either load it manually or perform a migration (update.php --update-schema)

### ISSUE THREAD

**Issue by aelg305** [lbouriez/hassio-addons#15]
## My AddOn personal config file yaml (comments welcome):

```
TTRSS_DB_TYPE: mysql
TTRSS_DB_HOST: core-mariadb
TTRSS_DB_USER: ttrss
TTRSS_DB_NAME: ttrss
TTRSS_DB_PASS: mysuperduperpasswordhere:)
TTRSS_DB_PORT: 3306
TTRSS_SELF_URL_PATH: https://ttrss.mydomain.com
```

# Problem/Motivation
Im able to access the addon from my custom domain....   (I did test from the local IP with self URL pointing and passing the test and got the same result)

However, Im getting this error message about the db:   SOLVED.....SEE BELOW!!!!!

`Base database schema is missing. Either load it manually or perform a migration (update.php --update-schema)`

## Steps to reproduce
- added addon repo
- installed ttrss addon
- mariadb addon (was already installed)
- updated credentials within mariadb: db_name, db_user, db-password
- updated config within ttrss
- started addon

## Proposed changes
See below ... not a change but a solution

**Comment by lbouriez** [comment]
Hello, it's been a while I worked on that... I mainly created it to have a backup of my pass rss feeds...
This being said, can you have a look here and try: https://github.com/serl/ttrss-heroku/issues/13
It could help you... else I have no idea, I already have my setup restored.
Let me know

**Comment by aelg305** [comment]
## Solution to fix message: `update.php --update-schema:`

Used SSH Addon: Advanced SSH & Web Terminal 
Ran: `docker ps`  -to find the name of the container ttrss is running and copy/write it down
Ran: `docker exec -it -u 1000 (name of container from above without parenthesis) /bin/bash`   - to attached the container and run the command to udpate the database
Ran:  `cd /var/www/html` - Change directory to where update.php is located
Ran: `php update.php --update-schema`
Got a few lines of code and message:  `Type 'yes' to continue. ` Typed: `yes`

DONE - I can access, if anybody needs help, let me know.
